version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - offgrid-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    networks:
      - offgrid-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=offgrid_db
      - POSTGRES_USER=offgrid_user
      - POSTGRES_PASSWORD=change_this_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - offgrid-network

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - offgrid-network

  # Optional: Meilisearch for full-text search
  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=change_this_master_key
    volumes:
      - meilisearch_data:/meili_data
    ports:
      - "7700:7700"
    networks:
      - offgrid-network

networks:
  offgrid-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  meilisearch_data:
